### ISSUE TITLE
Retcode = -1 all the time

### ISSUE THREAD

**Issue by annabellasd** [HighDimensionalEconLab/symmetry_dynamic_programming#13]
Retcode is always giving me `retcode = -1` even when it's an early stopping success. The code is working in the sense that it is doing what it should like if you see the print because the `cli.trainer.logger.experiment.summary[callback.monitor] > callback.stopping_threshold`. But clearly it is stopping before it hits the max epochs of 1000. Usually it will print something like 1.6 e-6 for the former and the stopping threshold is 1 e-6. So it should have early stopping failure = False right? but then the logic says it should be True?

https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/generalized_mean.py#L169-L174

(Also I think Im missing something: if the success threshold is 0 doesn't that mean we will never actually have an early stop so I don't get this logic https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/generalized_mean.py#L183-L184 
and why it automatically gives a retcode =0 https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/generalized_mean.py#L194-L198)

**Comment by jlperla** [comment]
We can't discuss this on the same branch as the plotting changes.  @Mekahou  you should have this one and we can go through it step-by-step.
