### ISSUE TITLE
dictionary vs list for batch parameter

### ISSUE THREAD

**Issue by annabellasd** [HighDimensionalEconLab/symmetry_dynamic_programming#14]
How much does the batch parameter we pass in being a list vs dictionary matter because https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/investment_euler.py#L167-L169 in investment euler is a dictionary whereas https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/generalized_mean.py#L75-L77 is a list and trying to change this was a bit above my abilities. By best guess is it came from the `def setup` https://github.com/HighDimensionalEconLab/symmetry_dynamic_programming/blob/Annabella_branch/investment_euler.py#L348-L364 

but I get really lost in trying to map between these two to make the generalized mean X, y_t also into a dictionary in a similar way so all the functions could be more consistent.

**Comment by jlperla** [comment]
@Mekahou   I think that you need to start off with a new github issue and go through changes methodically to map things over.  I can help if you end up confused... but you don't want to do this all at once and we can discuss things step by step if there are problems.
